### ISSUE TITLE
CURL Timeout with fake visits generator

### ISSUE THREAD

**Issue by httpbob** [matomo-org/plugin-VisitorGenerator#11]
Here is the following command line I have used:

./console visitorgenerator:generate-visits --idsite 1 --days 1 --piwik-domain http://www.me.lo:8001 --limit-fake-visits 2 -vvv

And the results:

[Exception]  
  curl_exec: Operation timed out after 5001 milliseconds with 0 bytes received. Hostname requested was ww.me.lo

I am in my dev environment and I am using the built-in PHP server listening on port 8001.

I tried to look in the source code of the plugin but I did ot find anything for now.

Please help !

**Comment by metrix78** [comment]
I have the exact issue and have looked everywhere for a workaround.  Any suggestions would be appreciated.

**Comment by rameshapsp** [comment]
I too tried it and getting the same error while trying to generate the visits

**Comment by rameshapsp** [comment]
I resolved this issue by adding the ipaddress of the system from which I am running the visitorgenerator command to the trusted_hosts[] = "192.168.140.128" inside the config.ini.php of the piwik root folder.

To be more precise

1. I checked the ip of the system (Ubuntu) by using "ifconfig" command.
2. Then I added the IP of the system to the trusted_hosts[]="192.168.140.128" inside the "config.ini.php" of the piwik installation.

That's all this resolved my issue in my case

**Comment by Beatrice084** [comment]
I get the same error: "curl_exec: Operation timed out after 5001 milliseconds with 0 bytes received. Hostname requested was: localhost"

**Comment by mikkeschiren** [comment]
This problem seems still to exist, getting mostly the same - looking into to set the timeout as an option, an higher default value.

**Comment by mikkeschiren** [comment]
Pull request: https://github.com/matomo-org/plugin-VisitorGenerator/pull/40

**Comment by mikkeschiren** [comment]
This is now committed to master branch. Hopefully this will be included in the next release.

**Comment by tsteur** [comment]
👍  will close the issue
