### ISSUE TITLE
Add possibility for plugins to hook into fake visits generation

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-VisitorGenerator#3]
Plugins should be able to generate visits/actions/parsms as well. For example in Bandwidth plugin I'd like to generate some pages with Bandwidth.

**Comment by heurteph-ei** [comment]
Hi,
It can be also interesting especially for Matomo plugins (ie developped by Matomo team).

[MarketingCampaignsReporting](https://plugins.matomo.org/MarketingCampaignsReporting#documentation) seems to not have hits generated: 
https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=Referrers_Referrers&subcategory=Referrers_Campaigns

*Campaign Sources*, *Campaign Contents*, *Campaign Ids*, *Campaign Placements*, *Campaign Mediums*, *Campaign Source - Medium* and *Campaign Groups* reports are empty... 😞

**Comment by AltamashShaikh** [comment]
This done with https://github.com/matomo-org/plugin-VisitorGenerator/pull/115
